OFP_TYPE_LIST = [
  'OFPT_HELLO', \
  'OFPT_ERROR', \
  'OFPT_ECHO_REQUEST', \
  'OFPT_ECHO_REPLY', \
  'OFPT_VENDOR', \
  'OFPT_FEATURES_REQUEST', \
  'OFPT_FEATURES_REPLY', \
  'OFPT_GET_CONFIG_REQUEST', \
  'OFPT_GET_CONFIG_REPLY',\
  'OFPT_SET_CONFIG', \
  'OFPT_PACKET_IN', \
  'OFPT_FLOW_REMOVED', \
  'OFPT_PORT_STATUS', \
  'OFPT_PACKET_OUT', \
  'OFPT_FLOW_MOD', \
  'OFPT_PORT_MOD', \
  'OFPT_STATS_REQUEST', \
  'OFPT_STATS_REPLY', \
  'OFPT_BARRIER_REQUEST', \
  'OFPT_BARRIER_REPLY', \
  'OFPT_QUEUE_GET_CONFIG_REQUEST', \
  'OFPT_QUEUE_GET_CONFIG_REPLY'
]
